SET VERIFY OFF;

DEFINE sid = &1
DEFINE pdb_name = &2
DEFINE pdb_user = &3
DEFINE pdb_password = &4

CREATE PLUGGABLE DATABASE "&pdb_name" ADMIN USER &pdb_user IDENTIFIED BY &pdb_password FILE_NAME_CONVERT=('/opt/oracle/oradata/&sid/pdbseed/','/opt/oracle/oradata/&sid/&pdb_name');
ALTER PLUGGABLE DATABASE "&pdb_name" OPEN;
ALTER PLUGGABLE DATABASE "&pdb_name" SAVE STATE;

ALTER SESSION SET CONTAINER="&pdb_name";
GRANT ALL PRIVILEGES TO &pdb_user;
ALTER PROFILE DEFAULT LIMIT password_life_time UNLIMITED;
SELECT resource_name, limit FROM dba_profiles WHERE PROFILE = 'DEFAULT';

ALTER TABLESPACE UNDOTBS1 OFFLINE;
DROP TABLESPACE UNDOTBS1 INCLUDING CONTENTS AND DATAFILES;
ALTER SESSION SET CONTAINER=CDB$ROOT;

