ALTER PROFILE DEFAULT LIMIT PASSWORD_REUSE_TIME UNLIMITED
;
ALTER PROFILE DEFAULT LIMIT PASSWORD_LIFE_TIME UNLIMITED
;
ALTER PROFILE DEFAULT LIMIT PASSWORD_GRACE_TIME UNLIMITED
;

CREATE USER scalified IDENTIFIED BY 123456
;
GRANT ALL PRIVILEGES TO scalified
;
