SHUTDOWN IMMEDIATE;

STARTUP UPGRADE;

ALTER DATABASE LOCAL UNDO OFF;

SHUTDOWN IMMEDIATE;

STARTUP;

SELECT * FROM database_properties WHERE property_name='LOCAL_UNDO_ENABLED';

ALTER SYSTEM SET PGA_AGGREGATE_LIMIT = 0;

ALTER SYSTEM SET PROCESSES=2000 SCOPE=SPFILE;

SHUTDOWN IMMEDIATE;

STARTUP;

